### PR TITLE
Specify brand support.

### PR DESCRIPTION
**Pull request by notlee**
https://github.com/Financial-Times/origami/issues/91

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-toggle bundle size difference from 2.1.2 to de84905fefb8f8927836266efd3d6fbe9018e52a
No significant bundle size differences found.

**Review by chee — APPROVED** [review]
the spec is a bit weird on this, it says:

> If a component supports brands, it must register the brands it supports under the brands property in its origami.json file. E.g. to support all three Origami brands add:

and

> Components which support brands must include the o-brand component as a dependency, which provides functions and mixins to customise a component per brand.

which makes it vague whether or not saying you support all brands without adding a dependency on o-brands is incompliant.

**Comment by notlee** [comment]
That is weird! Let's remove the o-brand requirement? It feels unnecessary.

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v2.1.3 :tada:

**Pull request merged**
